### ISSUE TITLE
여러 파일들을 사용하고 싶습니다.

### ISSUE THREAD

**Issue by plkmnb100** [UnderC/KKuTu#1]
안녕하세요. 모두끄투 공동 총관리자인 박찬영이라고 합니다.
저희 서버에 /setnick 기능, 기간밴 기능, ip밴 기능을 사용하고 싶습니다.
만일 허락하신다면, 어느 파일을 수정, 생성해야 하는지 알려주시면 감사하겠습니다.
무리한 부탁이었다면 죄송합니다.

**Comment by kimhj050326** [comment]
@plkmnb100 
안녕하세요, 제로끄투 공동책임자 입니다.
끄투월드때 위 레포지토리 서버인 하루끄투랑 합병되어, 소스의 권한은 UnderC 님 및 저희측에 있습니다.
소스 사용은 금지하오니, 참고 바랍니다.

**Comment by kimhj050326** [comment]
@plkmnb100
이슈 닫아주세요
